import katex from 'katex';
import { DOMParser } from '@xmldom/xmldom';
import { readZip, writeZip } from '@sew/study-storage';
import type { PptxDeck, PptxFormulaShape } from '@sew/study-domain';

const MATH_NS = 'http://schemas.openxmlformats.org/officeDocument/2006/math';
const A14_NS = 'http://schemas.microsoft.com/office/drawing/2010/main';
const MC_NS = 'http://schemas.openxmlformats.org/markup-compatibility/2006';

type MathNode = { name: string; children: MathNode[]; text?: string };
export type PptxMathConversion =
  | { supported: true; omml: string; inlineOmml: string }
  | { supported: false; reason: 'invalid-or-unsupported-latex' | 'unsupported-mathml-node' };

const decodeXml = (value: string): string =>
  value
    .replace(/&(#x[\da-f]+|#\d+|amp|lt|gt|quot|apos);/gi, (_entity, code: string) => {
      if (code === 'amp') return '&';
      if (code === 'lt') return '<';
      if (code === 'gt') return '>';
      if (code === 'quot') return '"';
      if (code === 'apos') return "'";
      const point =
        code[1]?.toLowerCase() === 'x'
          ? Number.parseInt(code.slice(2), 16)
          : Number.parseInt(code.slice(1), 10);
      if (
        !Number.isInteger(point) ||
        point <= 0 ||
        point > 0x10ffff ||
        (point >= 0xd800 && point <= 0xdfff)
      )
        throw new Error('invalid-xml-character');
      return String.fromCodePoint(point);
    })
    .replace(/&[^;\s]+;/g, () => {
      throw new Error('unknown-xml-entity');
    });

const xmlText = (value: string): string =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/** Parse only KaTeX's generated XML subset; external declarations/entities are never accepted. */
const parseMathMl = (xml: string): MathNode => {
  if (xml.length > 256_000 || /<!|<\?/.test(xml)) throw new Error('unsafe-xml');
  const root: MathNode = { name: '#root', children: [] };
  const stack = [root];
  const tokens = xml.match(/<[^>]*>|[^<]+/g) ?? [];
  if (tokens.join('') !== xml) throw new Error('malformed-xml');
  for (const token of tokens) {
    if (token.startsWith('</')) {
      const name = /^<\/([A-Za-z][\w.-]*)(?:\s*)>$/.exec(token)?.[1];
      if (!name || stack.length < 2 || stack.at(-1)?.name !== name)
        throw new Error('malformed-xml');
      stack.pop();
    } else if (token.startsWith('<')) {
      const match = /^<([A-Za-z][\w.-]*)(?:\s+[^<>]*?)?\s*(\/?)>$/.exec(token);
      if (!match) throw new Error('malformed-xml');
      const name = match[1]!;
      // Attributes are inert generated by KaTeX, but entity syntax must still be valid.
      const attributeChunk = token.slice(name.length + 1, token.length - (match[2] ? 2 : 1));
      decodeXml(attributeChunk.replace(/(?:"[^"]*"|'[^']*')/g, ''));
      const node: MathNode = {
        name: name.includes(':') ? name.slice(name.indexOf(':') + 1) : name,
        children: [],
      };
      stack.at(-1)!.children.push(node);
      if (!match[2]) stack.push(node);
    } else if (token) {
      stack.at(-1)!.children.push({ name: '#text', children: [], text: decodeXml(token) });
    }
  }
  if (stack.length !== 1 || root.children.length !== 1) throw new Error('malformed-xml');
  return root.children[0]!;
};

const leafText = (node: MathNode): string =>
  node.children
    .map((child) => (child.name === '#text' ? (child.text ?? '') : leafText(child)))
    .join('');
const run = (value: string): string =>
  `<m:r><m:t xml:space="preserve">${xmlText(value)}</m:t></m:r>`;
const group = (nodes: MathNode[]): string => nodes.map(toOmml).join('');

const toOmml = (node: MathNode): string => {
  const children = node.children.filter((child) => child.name !== '#text' || child.text?.trim());
  switch (node.name) {
    case '#text':
      return node.text ? run(node.text) : '';
    case 'math':
    case 'mrow':
    case 'mstyle':
    case 'semantics':
      return group(
        children.filter((child) => child.name !== 'annotation' && child.name !== 'annotation-xml'),
      );
    case 'mpadded':
    case 'mphantom':
      throw new Error('unsupported-mathml-node');
    case 'mi':
    case 'mn':
    case 'mo':
    case 'mtext':
    case 'ms':
      return run(leafText(node));
    case 'mspace':
      return run(' ');
    case 'msup':
      if (children.length !== 2) throw new Error('unsupported-mathml-node');
      return `<m:sSup><m:e>${toOmml(children[0]!)}</m:e><m:sup>${toOmml(children[1]!)}</m:sup></m:sSup>`;
    case 'msub':
      if (children.length !== 2) throw new Error('unsupported-mathml-node');
      return `<m:sSub><m:e>${toOmml(children[0]!)}</m:e><m:sub>${toOmml(children[1]!)}</m:sub></m:sSub>`;
    case 'msubsup':
      if (children.length !== 3) throw new Error('unsupported-mathml-node');
      return `<m:sSubSup><m:e>${toOmml(children[0]!)}</m:e><m:sub>${toOmml(children[1]!)}</m:sub><m:sup>${toOmml(children[2]!)}</m:sup></m:sSubSup>`;
    case 'mfrac':
      if (children.length !== 2) throw new Error('unsupported-mathml-node');
      return `<m:f><m:num>${toOmml(children[0]!)}</m:num><m:den>${toOmml(children[1]!)}</m:den></m:f>`;
    case 'msqrt':
      return `<m:rad><m:radPr><m:degHide m:val="1"/></m:radPr><m:deg/><m:e>${group(children)}</m:e></m:rad>`;
    case 'mroot':
      if (children.length !== 2) throw new Error('unsupported-mathml-node');
      return `<m:rad><m:deg>${toOmml(children[1]!)}</m:deg><m:e>${toOmml(children[0]!)}</m:e></m:rad>`;
    default:
      throw new Error('unsupported-mathml-node');
  }
};

/** KaTeX provides a mature LaTeX parser; this bridge deliberately accepts only mapped MathML. */
export const convertLatexToOmml = (latex: string): PptxMathConversion => {
  if (!latex.trim() || latex.length > 8_000)
    return { supported: false, reason: 'invalid-or-unsupported-latex' };
  try {
    const rendered = katex.renderToString(latex, {
      output: 'mathml',
      throwOnError: true,
      strict: 'error',
      trust: false,
      maxExpand: 1_000,
      maxSize: 20,
    });
    const mathMl = /<math\b[\s\S]*?<\/math>/.exec(rendered)?.[0];
    if (!mathMl) return { supported: false, reason: 'invalid-or-unsupported-latex' };
    const tree = parseMathMl(mathMl);
    const omml = toOmml(tree);
    if (!omml) return { supported: false, reason: 'invalid-or-unsupported-latex' };
    const inlineOmml = `<m:oMath>${omml}</m:oMath>`;
    return {
      supported: true,
      omml: `<m:oMathPara>${inlineOmml}</m:oMathPara>`,
      inlineOmml,
    };
  } catch (error) {
    return {
      supported: false,
      reason:
        error instanceof Error && error.message === 'unsupported-mathml-node'
          ? 'unsupported-mathml-node'
          : 'invalid-or-unsupported-latex',
    };
  }
};

const nativeShape = (shapeXml: string, omml: string): string => {
  const txBody =
    '<p:txBody><a:bodyPr/><a:lstStyle/><a:p><a14:m>' + omml + '</a14:m></a:p></p:txBody>';
  const choiceShape = shapeXml.replace(/<p:txBody>[\s\S]*?<\/p:txBody>/, txBody);
  if (choiceShape === shapeXml) throw new Error('pptx_formula_shape_missing_text_body');
  return `<mc:AlternateContent xmlns:mc="${MC_NS}" xmlns:a14="${A14_NS}" xmlns:m="${MATH_NS}"><mc:Choice Requires="a14">${choiceShape}</mc:Choice><mc:Fallback>${shapeXml}</mc:Fallback></mc:AlternateContent>`;
};

const decodeTextNode = (value: string): string =>
  value.replace(/&(#x[\da-f]+|#\d+|amp|lt|gt|quot|apos);/gi, (_entity, code: string) => {
    if (code === 'amp') return '&';
    if (code === 'lt') return '<';
    if (code === 'gt') return '>';
    if (code === 'quot') return '"';
    if (code === 'apos') return "'";
    const point =
      code[1]?.toLowerCase() === 'x'
        ? Number.parseInt(code.slice(2), 16)
        : Number.parseInt(code.slice(1), 10);
    return Number.isInteger(point) && point >= 0 && point <= 0x10ffff
      ? String.fromCodePoint(point)
      : '';
  });

const nativeInlineShape = (
  shapeXml: string,
  shape: Extract<PptxDeck['slides'][number]['shapes'][number], { kind: 'text' }>,
): { xml: string; converted: number; unsupported: number } => {
  let converted = 0;
  let unsupported = 0;
  const formulas = shape.runs.filter((run) => run.formula);
  if (!formulas.length) return { xml: shapeXml, converted, unsupported };
  let result = shapeXml;
  for (const run of formulas) {
    const conversion = run.formula?.latex ? convertLatexToOmml(run.formula.latex) : null;
    if (!conversion?.supported) {
      unsupported += 1;
      continue;
    }
    let found = false;
    const replaced = result.replace(/<a:r\b[^>]*>[\s\S]*?<\/a:r>/g, (textRun) => {
      if (found) return textRun;
      const text = /<a:t\b[^>]*>([\s\S]*?)<\/a:t>/.exec(textRun)?.[1];
      if (text === undefined || decodeTextNode(text) !== run.text) return textRun;
      found = true;
      return `<a14:m>${conversion.inlineOmml}</a14:m>`;
    });
    if (!found) {
      throw new Error('pptx_inline_formula_mapping_failed');
    }
    converted += 1;
    result = replaced;
  }
  if (!converted) return { xml: shapeXml, converted, unsupported };
  return {
    xml: `<mc:AlternateContent xmlns:mc="${MC_NS}" xmlns:a14="${A14_NS}" xmlns:m="${MATH_NS}"><mc:Choice Requires="a14">${result}</mc:Choice><mc:Fallback>${shapeXml}</mc:Fallback></mc:AlternateContent>`,
    converted,
    unsupported,
  };
};

/** Inject native PowerPoint DrawingML math under an AlternateContent choice, retaining the editable source as fallback. */
export const injectNativeMath = (pptx: Uint8Array, deck: PptxDeck): Uint8Array => {
  const conversions = new Map<string, PptxMathConversion>();
  for (const slide of deck.slides) {
    for (const shape of slide.shapes) {
      if (shape.kind === 'formula' && shape.latex)
        conversions.set(shape.shapeId, convertLatexToOmml(shape.latex));
    }
  }
  const hasInlineFormulas = deck.slides.some((slide) =>
    slide.shapes.some((shape) => shape.kind === 'text' && shape.runs.some((run) => run.formula)),
  );
  if (![...conversions.values()].some((item) => item.supported) && !hasInlineFormulas) return pptx;
  const parts = readZip(pptx, { allowEmptyDirectories: true });
  const replaced = new Set<string>();
  let injectedCount = 0;
  const output = parts.map((part) => {
    const slideMatch = /^ppt\/slides\/slide(\d+)\.xml$/.exec(part.path);
    if (!slideMatch) return { path: part.path, bytes: part.bytes };
    const slide = deck.slides[Number(slideMatch[1]) - 1];
    if (!slide) return { path: part.path, bytes: part.bytes };
    let xml = Buffer.from(part.bytes).toString('utf8');
    for (const shape of slide.shapes) {
      if (shape.kind !== 'formula' && shape.kind !== 'text') continue;
      const conversion = shape.kind === 'formula' ? conversions.get(shape.shapeId) : null;
      if (
        (shape.kind === 'formula' && (!shape.latex || !conversion?.supported)) ||
        (shape.kind === 'text' && !shape.runs.some((run) => run.formula))
      )
        continue;
      const marker = `name="${shape.shapeId}"`;
      const markerAt = xml.indexOf(marker);
      const shapeStart = markerAt < 0 ? -1 : xml.lastIndexOf('<p:sp>', markerAt);
      const shapeEndAt = markerAt < 0 ? -1 : xml.indexOf('</p:sp>', markerAt);
      const match =
        markerAt >= 0 && shapeStart >= 0 && shapeEndAt >= 0
          ? { index: shapeStart, text: xml.slice(shapeStart, shapeEndAt + '</p:sp>'.length) }
          : null;
      if (!match || xml.indexOf(marker, markerAt + 1) !== -1 || replaced.has(shape.shapeId))
        throw new Error('pptx_formula_shape_not_unique');
      const originalShape = match.text;
      const native =
        shape.kind === 'formula'
          ? {
              xml: nativeShape(originalShape, conversion?.supported ? conversion.omml : ''),
              converted: 1,
            }
          : nativeInlineShape(originalShape, shape);
      if (native.xml !== originalShape) {
        xml =
          xml.slice(0, match.index) + native.xml + xml.slice(match.index + originalShape.length);
        replaced.add(shape.shapeId);
        injectedCount += shape.kind === 'formula' ? 1 : native.converted;
      }
    }
    return { path: part.path, bytes: Buffer.from(xml, 'utf8') };
  });
  const expectedCount =
    [...conversions.values()].filter((item) => item.supported).length +
    deck.slides.reduce(
      (total, slide) =>
        total +
        slide.shapes.reduce(
          (count, shape) =>
            count +
            (shape.kind === 'text'
              ? shape.runs.filter(
                  (run) => run.formula?.latex && convertLatexToOmml(run.formula.latex).supported,
                ).length
              : 0),
          0,
        ),
      0,
    );
  if (injectedCount !== expectedCount) throw new Error('pptx_formula_readback_failed');
  return Uint8Array.from(writeZip(output));
};

export const formulaConversion = (shape: PptxFormulaShape): PptxMathConversion =>
  shape.representation === 'native-math' && shape.latex
    ? convertLatexToOmml(shape.latex)
    : { supported: false, reason: 'invalid-or-unsupported-latex' };

export const summarizePptxFormulaSupport = (
  deck: PptxDeck,
): {
  converted: number;
  unsupported: number;
  convertedInline: number;
  unsupportedInline: number;
} => {
  let converted = 0;
  let unsupported = 0;
  let convertedInline = 0;
  let unsupportedInline = 0;
  for (const slide of deck.slides) {
    for (const shape of slide.shapes) {
      if (shape.kind === 'formula') {
        if (formulaConversion(shape).supported) converted += 1;
        else unsupported += 1;
      } else if (shape.kind === 'text') {
        for (const run of shape.runs) {
          if (!run.formula) continue;
          if (run.formula.latex && convertLatexToOmml(run.formula.latex).supported)
            convertedInline += 1;
          else unsupportedInline += 1;
        }
      }
    }
  }
  return { converted, unsupported, convertedInline, unsupportedInline };
};

/** Parse a slide read back from the PPTX ZIP and count the namespace-qualified native math nodes. */
export const inspectPptxMathXml = (
  slideXml: string,
): {
  alternateContent: number;
  mathExtensions: number;
  mathObjects: number;
} => {
  const errors: string[] = [];
  const document = new DOMParser({
    errorHandler: (level, message) => errors.push(`${level}:${message}`),
  }).parseFromString(slideXml, 'application/xml');
  if (errors.length || document.getElementsByTagName('parsererror').length)
    throw new Error('pptx_math_xml_parse_failed');
  return {
    alternateContent: document.getElementsByTagNameNS(MC_NS, 'AlternateContent').length,
    mathExtensions: document.getElementsByTagNameNS(A14_NS, 'm').length,
    mathObjects: document.getElementsByTagNameNS(MATH_NS, 'oMath').length,
  };
};
