/** Stable HTTP contract exports; schemas are owned by their feature modules. */
export { projectScopeSchema } from './http/project';
export type { ProjectScope } from './http/project';
export { projectSettingsPatchSchema } from './http/project';
export type { ProjectSettingsPatchInput } from './http/project';
export { materialImportFileSchema } from './http/material';
export type { MaterialImportFileInput } from './http/material';
export { materialImportTextSchema } from './http/material';
export type { MaterialImportTextInput } from './http/material';
export { materialImportSchema } from './http/material';
export type { MaterialImportInput } from './http/material';
export { materialRawArchiveSchema } from './http/material';
export type { MaterialRawArchiveDto } from './http/material';
export { materialSchema } from './http/material';
export type { MaterialDto } from './http/material';
export { segmentSchema } from './http/material';
export type { SegmentDto } from './http/material';
export { materialRawQuerySchema } from './http/material';
export type { MaterialRawQuery } from './http/material';
export { materialRawViewSchema } from './http/material';
export type { MaterialRawViewDto } from './http/material';
export { materialOriginalOpenSchema } from './http/material';
export type { MaterialOriginalOpenInput } from './http/material';
export { materialExamVerificationSchema } from './http/material';
export type { MaterialExamVerificationInput } from './http/material';
export { evidenceRefSchema } from './http/knowledge';
export type { EvidenceRefInput } from './http/knowledge';
export { knowledgeProposeSchema } from './http/knowledge';
export type { KnowledgeProposeInput } from './http/knowledge';
export { mechanicalCheckSchema } from './http/knowledge';
export type { MechanicalCheckDto } from './http/knowledge';
export { proposalSchema } from './http/knowledge';
export type { ProposalDto } from './http/knowledge';
export { reviewApplySchema } from './http/knowledge';
export type { ReviewApplyInput } from './http/knowledge';
export { knowledgePointSchema } from './http/knowledge';
export type { KnowledgePointDto } from './http/knowledge';
export { syllabusRequirementSchema } from './http/syllabus';
export type { SyllabusRequirementInput } from './http/syllabus';
export { syllabusMappingSchema } from './http/syllabus';
export type { SyllabusMappingInput } from './http/syllabus';
export { syllabusItemCreateSchema } from './http/syllabus';
export type { SyllabusItemCreateInput } from './http/syllabus';
export { syllabusItemSchema } from './http/syllabus';
export type { SyllabusItemDto } from './http/syllabus';
export { syllabusCoverageItemSchema } from './http/syllabus';
export type { SyllabusCoverageItemDto } from './http/syllabus';
export { syllabusCoverageSchema } from './http/syllabus';
export type { SyllabusCoverageDto } from './http/syllabus';
export { admissionCheckSchema } from './http/admission';
export type { AdmissionCheckInput } from './http/admission';
export { admissionResultSchema } from './http/admission';
export type { AdmissionResultDto } from './http/admission';
export { questionCreateSchema } from './http/question';
export type { QuestionCreateInput } from './http/question';
export { questionListItemSchema } from './http/question';
export type { QuestionListItemDto } from './http/question';
export { questionSchema } from './http/question';
export type { QuestionDto } from './http/question';
export { questionDetailQuerySchema } from './http/question';
export type { QuestionDetailQuery } from './http/question';
export { classroomSceneBindingSchema } from './http/classroom';
export type { ClassroomSceneBinding } from './http/classroom';
export { interactionDirectionSchema } from './http/classroom';
export { interactionSubmitSchema } from './http/classroom';
export type { InteractionSubmitInput } from './http/classroom';
export { interactionPayloadSchema } from './http/classroom';
export { interactionSubmissionSchema } from './http/classroom';
export type { InteractionSubmissionDto } from './http/classroom';
export { interactionStateSchema } from './http/classroom';
export type { InteractionStateDto } from './http/classroom';
export { classroomAssetInfoSchema } from './http/classroom';
export type { ClassroomAssetInfoDto } from './http/classroom';
export { assetReclaimReportSchema } from './http/classroom';
export type { AssetReclaimReportDto } from './http/classroom';
export { assetReclaimSchema } from './http/classroom';
export type { AssetReclaimInput } from './http/classroom';
export { assetReclaimResultSchema } from './http/classroom';
export type { AssetReclaimResultDto } from './http/classroom';
export { attemptSubmitSchema } from './http/attempt';
export type { AttemptSubmitInput } from './http/attempt';
export { attemptSchema } from './http/attempt';
export type { AttemptDto } from './http/attempt';
export { workbenchStateSchema } from './http/workbench';
export type { WorkbenchStateDto } from './http/workbench';
export { preferencesSchema } from './http/preferences';
export type { PreferencesDto } from './http/preferences';
export { teachingPreferenceSchema } from './http/preferences';
export type { TeachingPreferenceDto } from './http/preferences';
export { preferencesWriteSchema } from './http/preferences';
export type { PreferencesWriteInput } from './http/preferences';
export { rolePermissionsSchema } from './http/role';
export type { RolePermissionsDto } from './http/role';
export { roleProfileSchema } from './http/role';
export type { RoleProfileDto } from './http/role';
export { roleCreateSchema } from './http/role';
export type { RoleCreateInput } from './http/role';
export { roleUpdateSchema } from './http/role';
export type { RoleUpdateInput } from './http/role';
export { roleDeleteSchema } from './http/role';
export type { RoleDeleteInput } from './http/role';
export { recentProjectSchema } from './http/recent-project';
export type { RecentProjectDto } from './http/recent-project';
export type { ApiSuccess } from './http/envelope';
export type { ApiFailure } from './http/envelope';
export type { ApiEnvelope } from './http/envelope';
